CREATE DATABASE QL_CUAHANG

CREATE TABLE PHANQUYEN(
	MAPHANQUYEN INT PRIMARY KEY,
	MANHINH NVARCHAR(50),
	CHUTHICH NVARCHAR(100)
)

CREATE TABLE NHANVIEN(
	MANV int identity(1,1) PRIMARY KEY,
	TENDN NVARCHAR(50) ,
	MATKHAU NVARCHAR(100),
	TENNV NVARCHAR(100),
	DIACHI NVARCHAR(100),
	DIENTHOAI INT,
	MAPHANQUYEN INT,
	CHUTHICH NVARCHAR(100),
	constraint FK_NV_QUYEN foreign key (MAPHANQUYEN) references PHANQUYEN(MAPHANQUYEN),
)
CREATE TABLE KHACHHANG(
	MAKHACHHANG int identity(1,1) PRIMARY KEY,
	TENKHACHHANG NVARCHAR(100),
	DIACHI NVARCHAR(MAX),
	DIENTHOAI INT,
	EMAIL NVARCHAR(50) NULL,
)

CREATE TABLE NHOMHANG(
	MANHOMHANG NVARCHAR(50) PRIMARY KEY,
	TENNHOMHANG NVARCHAR(100),
)
CREATE TABLE LOAIHANG(
	MALOAI NVARCHAR(50) PRIMARY KEY,
	MANHOMHANG NVARCHAR(50),
	TENLOAI NVARCHAR(100),
	constraint FK_LOAIHANG_NHOMHANG  foreign key (MANHOMHANG) references NHOMHANG(MANHOMHANG),
)
CREATE TABLE KHOHANG(
	MAHANG NVARCHAR(50) PRIMARY KEY,
	MALOAI NVARCHAR(50),
	TENHANG NVARCHAR(100),
	HINHANH NVARCHAR(MAX),
	DONGIA MONEY,
	SOLUONG INT,
	BAOHANH INT,
	constraint FK_KHOHANG_LOAIHANG  foreign key (MALOAI) references LOAIHANG(MALOAI),
)
CREATE TABLE BAOHANH(
	MABAOHANH int identity(1,1) PRIMARY KEY,
	MAKHACHHANG int,
	MAHANG NVARCHAR(50),
	YEUCAUBAOHANH NVARCHAR(MAX),
	NGAYNHAN DATETIME ,
	NGAYTRA DATETIME ,
	constraint FK_BAOHANH_KHOHANG foreign key (MAHANG) references KHOHANG(MAHANG),
)
CREATE TABLE NHACUNGCAP(
	MANCC int identity(1,1) PRIMARY KEY,
	TENNCC NVARCHAR(100) ,
	DIACHI NVARCHAR(100),
	DIENTHOAI INT,
	CHUTHICH NVARCHAR(100),
)
CREATE TABLE PHIEUNHAP
(
	MAPN int identity(1,1) PRIMARY KEY,
	MANV int,
	MANCC int,
	NGAYLAP DATETIME,
	constraint FK_PHIEUNHAP_NV foreign key (MANV) references NHANVIEN(MANV),
	constraint FK_PHIEUNHAP_NCC  foreign key (MANCC) references NHACUNGCAP(MANCC),
)
CREATE TABLE CHITIETPHIEUNHAP(
	MACTPN int ,
	MAHANG NVARCHAR(50),
	SOLUONG INT,
	DONGIA MONEY,
	THANHTIEN MONEY,
	CONSTRAINT PK_CHITIETPHIEUNHAP PRIMARY KEY (MACTPN, MAHANG),
	constraint FK_CHITIETPHIEUNHAP_PHIEUNHAP foreign key (MACTPN) references PHIEUNHAP(MAPN),
	constraint FK_CHITIETPHIEUNHAP_KHOHANG  foreign key (MAHANG) references KHOHANG(MAHANG),
)
CREATE TABLE PHIEUCHI(
	MAPHIEUCHI int identity(1,1) PRIMARY KEY,
	MAPN int ,
	MANCC int ,
	TONGTIEN MONEY,
	NGAYCHI DATETIME NULL,
	CHUTHICH NVARCHAR(MAX),
	constraint FK_PHIEUCHI_PHIEUNHAP foreign key (MAPN) references PHIEUNHAP(MAPN),
	constraint FK_PHIEUCHI_NCC  foreign key (MANCC) references NHACUNGCAP(MANCC),
)
CREATE TABLE PHIEUXUAT(
	MAPHIEUXUAT int identity(1,1) PRIMARY KEY,
	MAKHACHHANG int,
	MANV int ,
	NGAYLAPPHIEU DATETIME,
	constraint FK_PHIEUXUAT_MAKHACHHANG foreign key (MAKHACHHANG) references KHACHHANG(MAKHACHHANG),
	constraint FK_PHIEUXUAT_NHANVIEN  foreign key (MANV) references NHANVIEN(MANV),
)
CREATE TABLE CHITIETPHIEUXUAT(
	MACTPHIEUXUAT INT, 
	MAHANG NVARCHAR(50),
	DONGIA MONEY,
	SOLUONG INT,
	THANHTIEN MONEY,
	CHUTHICH NVARCHAR(50),
	CONSTRAINT PK_CHITIETPHIEUXUAT PRIMARY KEY (MACTPHIEUXUAT, MAHANG),
	constraint FK_CHITIETPHIEUXUAT_PHIEUXUAT foreign key (MACTPHIEUXUAT) references PHIEUXUAT(MAPHIEUXUAT),
	constraint FK_CHITIETPHIEUXUAT_KHOHANG  foreign key (MAHANG) references KHOHANG(MAHANG),
)
CREATE TABLE PHIEUTHU(
	MAPHIEUTHU int identity(1,1) PRIMARY KEY,
	MAPHIEUXUAT int,
	NGAYTHU DATETIME,
	TONGTIEN MONEY,
	constraint FK_PHIEUTHU_PHIEUXUAT foreign key (MAPHIEUXUAT) references PHIEUXUAT(MAPHIEUXUAT),
)
